### ISSUE TITLE
gradle dependencies please

### ISSUE THREAD

**Issue by azizimusa** [JesusM/HoloCircleSeekBar#8]

**Comment by JesusM** [comment]
Please, add in the description what do you want/suggest, because the title doesn't provide enough information about the problem.

**Comment by jitpack-io** [comment]
Suspecting that @azizimusa is referring to gradle install instructions. Not sure about your releases ibut at the moment it's already available as a Gradle dependency:
https://jitpack.io/#JesusM/HoloCircleSeekBar/d724180c19 :)

Would be a even nicer if there was a GitHub release of HoloCircleSeekBar so that we could use a version number.

**Comment by JesusM** [comment]
@jitpack-io Could you check that https://github.com/JesusM/HoloCircleSeekBar/releases fits with what you meant with `Would be a even nicer if there was a GitHub release of HoloCircleSeekBar so that we could use a version number.` ?

**Comment by jitpack-io** [comment]
@JesusM It does and works great https://jitpack.io/#JesusM/HoloCircleSeekBar

**Comment by JesusM** [comment]
Then I think I can close it for now
